### ISSUE TITLE
Libki client timer not working

### ISSUE THREAD

**Issue by rommelcalizotupig** [Libki/libki-client#3] opened 2016-12-02 06:56 UTC
Hi,

I successfully installed libki server, i can login to the client with the correct time allotted, however the client timer is not working and does not show any activity when the amount of time allotted is consumed. Can you please help.  My platform are both windows.

Thanks.

**Comment by toomk** [comment] 2017-04-21 12:43
Same problem here. Server on Debian 8, and client on windows 8. The time isn't counting down.

**Comment by kylemhall** [comment] 2017-04-21 18:46
Are you sure you have the two Libki cronjobs set to run? The one that
counts down time is supposed to be run every minute, the libki_nightly.pl
one should be run each night. Both are meant to be run from your crontab.

Kyle

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by toomk** [comment] 2017-04-24 07:20
Hey, Kyle!

I'll check right away if it's set up correctly, I did a reinstall and maybe I missed something. 

tomk

**Comment by toomk** [comment] 2017-04-24 08:05
The cronjobs seems to work just fine.  No count down nor cron errors. 

Though I get this in the libki.log:

> [2017/04/24 07:42:43] [libki] [WARN] DBIx::Class cursor caching disabled, you don't seem to have a working Cache plugin.

Quite odd. Haven't seen that one before.

**Comment by toomk** [comment] 2017-04-24 08:06
By the way: I did the manual installation.

**Comment by toomk** [comment] 2017-04-24 10:11
Maybe I should post this as a seperate issue, because I doubt that it has anything to do with the above one.  This error is spamming my libki_server.log - even after I've killed the libki process:

> 
Error while loading /home/libki/libki-server/libki.psgi: Can't open /home/port_orford/libki.log (No such file or directory) at /home/libki/perl5/lib/perl5/Log/Log4perl/Appender/File.pm line 151.
Compilation failed in require at /home/libki/libki-server/libki.psgi line 4.
BEGIN failed--compilation aborted at /home/libki/libki-server/libki.psgi line 4.
new worker 3459 seems to have failed to start, exit status:512
starting new worker 3460

I tried to change the directory path where it's located in the log4perl file but it doesn't have any effect at all. No idea where that "port_orford" path comes from!

**Comment by kylemhall** [comment] 2017-04-24 10:42
That is almost certainly the root cause of your issue. I would recommend
you change /home/port_orford/libki.log to /var/log/libki/libki.log, and
make sure that file is writable by the libki processes ( i.e. chown
libki.libki /var/log/libki/libki.log ) then restart the sever.

Kyle

On Mon, Apr 24, 2017 at 6:11 AM, toomk <notifications@github.com> wrote:

> /home/port_orford/libki.log




<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by toomk** [comment] 2017-04-24 10:57
Ok, I just find one place to change the path and it's:

> /home/libki/libki-server/log4perl.conf 

And that's what I tried to change earlier, but still got that port_orford error in log. And the same thing happens now after a restart of the server.

**Comment by kylemhall** [comment] 2017-04-24 13:29
Try changing the value in that file to /tmp/libki.log and restart your
server.

Kyle

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by toomk** [comment] 2017-04-24 13:34
Clarification: I did not put "/home/libri/port_orford" as path in the first place. 

Anyway, I didn't say it earlier but thanks for the response. Means a lot. Got huge hopes to use Libki in my institution(library), instead the proprietary expansive piece of garbage software we've been using **for many years now!** ;)

**Comment by toomk** [comment] 2017-04-24 14:13
Anyway, same thing with "/tmp/libki.log". Still getting:

> Error while loading /home/libki/libki-server/libki.psgi: Can't open /home/port_orford/libki.log (No such file or directory) at /home/libki/perl5/lib/perl5/Log/Log4perl/Appender/File.pm line 151.
...

It really doesn't seem to matter what I change the path to in "/home/libki/libki-server/log4perl.conf". Pretty odd.

**Comment by kylemhall** [comment] 2017-04-24 15:56
It sounds like you are not restarting the Libki server. Did you set up the
init script? If so, run "sudo /etc/init.d/libki restart".

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by toomk** [comment] 2017-04-25 07:27
I agree, it does sound like that. However, I've done it and the Libki init script works fine. Even rebooted the server a few times to be sure. But the mysterious port_orford path still prevails.

**Comment by kylemhall** [comment] 2017-04-25 12:20
Ok, cd into your Libki source code directory and then run "grep -ir "orford"
and let me know what the results are.

Kyle

On Tue, Apr 25, 2017 at 3:27 AM, toomk <notifications@github.com> wrote:

> port_orford




<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by kylemhall** [comment] 2017-04-25 12:20
Oops, the command should be:

grep -ir orford .

Kyle

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by toomk** [comment] 2017-04-25 12:51
Good day, Kyle

If I do that from /home/libki/libki-server/ I get nothing! 

With:

`grep` --exclude=*.log -ir orford .

I find absolutely nothing.
Not even with a total system scan:

`find` / -xdev -type f -print0 | xargs -0 grep --exclude=*.log  -H "orford"

The only place I can find the string "port_orford" is in the log4perl.conf and it's not there anymore.
 I really can't understand how it's possible! o_0

**Comment by kylemhall** [comment] 2017-04-25 13:41
Wow, I also can't say I have any idea at all what could be going on. Try
this in your Libki directory:

git reset --hard
git fetch origin
git checkout origin/master

Then reboot your server.

Kyle

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by toomk** [comment] 2017-04-26 07:25
Good morning Kyle,

Nothing new, I'm afraid. It's still spamming the libki_server.log with

```
Error while loading /home/libki/libki-server/libki.psgi: Can't open /home/port_orford/libki.log (No such file or directory) at /home/libki/perl5/lib/perl5/Log/Log4perl/Appender/File.pm line 151.
Compilation failed in require at /home/libki/libki-server/libki.psgi line 4.
BEGIN failed--compilation aborted at /home/libki/libki-server/libki.psgi line 4.
new worker 4962 seems to have failed to start, exit status:512
starting new worker 4963
```

**Comment by toomk** [comment] 2017-04-27 09:44
But I mean, the "port_orford" **must** come from somewhere, right? It's also kind of strange that it's a user account(/home/port_orford/) - I have never ever made a account with that name, and the VM I on is setup just for this so it should be clean. And the tech guy that set it up says he never heard of 'port_orford' either. Maybe I should try to make a port_orford user to see what happens. It won't bring me answers but it might get things to work. Need to do try something to move forward.

**Comment by toomk** [comment] 2017-04-28 10:12
Kyle!

It's silly, but I'd missread the logs because of lack of timestamps and it's enormous size, and thought it got updated even though it didn't. I'm pretty sure that he port-orford error was fixed by the change in log4perl.conf I did last week... *sigh* 

I can see that someone commited the change to the log4perl.conf in master branch. 
 
I'm going to do a total rollback now and do a fresh clone - there been some changes since my first install. Hopefully it will fix my initial problem with the timer not counting down as well.

Anyway, sorry bout spreading my confusion.

/tomk

**Closed** 2018-05-15 14:38 UTC
