### ISSUE TITLE
Windows 10 client closing session

### ISSUE THREAD

**Issue by heyitsjoewevers** [Libki/libki-client#5] opened 2017-01-04 21:19 UTC
Hi,
I just installed the server on debian jessie and client on win 10. Both are VM's for testing. Does Libki's client have some sort of problem with VM's or with a new windows 10 patch? The issue I'm getting is the client is logging itself out after a few moments and showing the default libki client login screen. I can still login with any of the accounts, but I am logged out soon after. When it is logging out the clock drops from whatever the set time is to 0, then logs the user out. Any suggestions would be great.
Thanks!

**Comment by YiMeChen** [comment] 2017-02-23 14:47
@heyitsjoewevers i had the same exact problem following the docker-based setup via the server repository.. I'm not that familiar with docker, but going thru their manual setup instructions and ensure the cronjob for libki-server/script/cronjobs/libki.pl performs without error worked.

**Comment by MrMcMister** [comment] 2017-12-22 22:08
Having the same issue with debian server in a vm and a windows 10 client. No solution found yet and I have confirmed the cronjobs are running properly from the syslog. Not sure if the issue is client or server end. Haven't tested with a windows 7 client, but I'll be trying that soon.

**Comment by heyitsjoewevers** [comment] 2017-12-23 00:10
Sorry I should have given my solution earlier. The newest Libki client seems to be broken in win10. If you install and use the earlier versions, this problem does not exist.

**Comment by MrMcMister** [comment] 2017-12-23 15:40
thanks heyitsjoewevers, thats helpful. I found the issue in the latest client also occurs in a win 7 vm that I tested as well.

**Comment by kylemhall** [comment] 2018-05-15 14:37
Closing for now. If this problem shows up in the latest client installer let me know!

**Closed by kylemhall** 2018-05-15 14:37 UTC
