### ISSUE TITLE
Special characters not decoded

### ISSUE THREAD

**Issue by fribeiro-keeps** [Libki/libki-client#69] opened 2021-04-27 11:12 UTC
**Description**
Terms of service text is not decoded.

**To Reproduce**
1. Fill the Terms of service with "João Cação"
2. Login on a client
3. You will see the Terms like "JoÃ£o CaÃ§Ã£o"

**Expected behavior**
You should see "João Cação".

**Comment by kylemhall** [comment] 2021-04-27 12:57
Closing this issue and moving it to the libki-server repo, as it turns out the problem is on the server side.

**Closed by kylemhall** 2021-04-27 12:57 UTC
